from typing import Any, Callable, Optional

class PydanticSerializer: ...

class TriggerEvent: ...

class Context: ...

class Inngest:
    def __init__(self, app_id: str, logger: Any, is_production: bool = False, serializer: Optional[Any] = None) -> None: ...
    def create_function(self, fn_id: str = None, trigger: Any = None) -> Callable[..., Any]: ...
